name : Calculator CI/CD

on:
    push:
        branches : 
            - main

    pull_request:
        branches : 
            - main
        
    workflow_dispatch: #for button

    schedule:
        - cron : "*/5 * * * *" #everyday every 5 min

    # Task 8 additions: release: & create:
    #   trigger at GitHub UI creating release & publishing release
    release:
        types: [created, published]
    
    # trigger at GitHub when creating a feature branch, and
    # trigger when pushing to a feature branch: 
    # as in, 'git push origin <featurebranch>
    create:

jobs:
    build: #label for job
        runs-on : ubuntu-latest
        steps:
            - name : Checkout Code
              uses : actions/checkout@v4

            - name : Setup Node
              uses : actions/setup-node@v4
              with:
                node-version : 20
            
            - name : Install Dependencies
              run : npm install

            - name : Run ESLint
              run : npm run lint

            - name : Run JestTests
              run : npm test

            - name : Build Project
              run : echo "Building Application"

            - name : Deploy Project
              run : echo "Deploying Successfully"

            - name : Show Node Version
              run : node --version

            - name : Show NPM Version
              run : npm --version

            - name : Show Event
              run : echo "Triggered by ${{ github.event_name }}"

            - name : Show Date
              run : date


    nightly-build: #label for nightly build job
            runs-on: ubuntu-latest
            if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

            steps:
                - name: Show Event
                  run: echo "Triggered by ${{ github.event_name }}"

                - name : Generate report
                  run: echo "Generating Report"
    
    hello:
        runs-on : ubuntu-latest
        steps:
            - name : Print Message
              run : echo "Hello Students"